Added general velocity tools
uw-midsun/strategy_xv pull request #13
Opened 2022-11-15 08:15 UTC by ryan-lam

Added general velocity tools, docs, tests

- function to change speed, bearing, elevation to vectors
- function to project vectors

2022-11-17 01:10 UTC, probro27 reviewed
Hey @ryan-lam this looks pretty good. Though I am not sure, is there anywhere we want to use such a vector? Or is this just to help us visualize things?
Just want to understand the need of this as I am not currently sure where we would use this?
Thanks :)

2022-11-17 01:27 UTC, ryan-lam commented
Yea, it'll be used. I'm still working on the code that uses it. It's in another branch (https://github.com/uw-midsun/strategy_xv/blob/car-forces/routemodel/carforces/carforces.py) to do vector math and calculate vector projections

It's used in calculating the force on the car and any code related to velocities (ie. wind speed)

2022-11-17 01:30 UTC, probro27 requested changes
Cool, I just want you to update the documentation a bit for this. The rest looks amazing and I can see why you would need this. Thanks a lot. 
Great job!

2022-11-17 01:30 UTC, probro27 commented on routemodel/tools/README.md
> +# Tools.py: General tools that may be useful throughout dev
Please add some more documentation as to how the vector looks and what we are returning. 
Provide a couple of examples with calculations (if possible).

2022-11-18 05:58 UTC, probro27 approved these changes
LGTM!
Great job @ryan-lam. 
Merging it in :)

2022-11-18 05:58 UTC, merged