STRAT15-49 done elevations model/api
uw-midsun/strategy_xv pull request #5
Opened 2022-10-13 18:50 UTC by ryan-lam

2022-10-15 17:20 UTC, aliciabremer commented on routemodel/elevations/README.md
> +## User Guide
Documentation looks really good - very easy to follow for anyone wanting to run the code. Great work!

2022-10-15 17:33 UTC, aliciabremer requested changes
Looks great overall! I just had a couple tiny changes/comments, and once those are done, this is probably good to merge in.

2022-10-15 17:33 UTC, aliciabremer commented on routemodel/elevations/elevations.py
> +    def get_elevations(self, start_point: int = None, end_point: int = None):
As this data will probably used in a dataframe, it would be great to also have a separate function that can call this one but returns the data as a dataframe

2022-10-15 17:33 UTC, aliciabremer commented on routemodel/elevations/elevations.py
> +    def plot_elevations(self, start_point: int = None, end_point: int = None):
This works really well - nice job!

2022-10-15 17:33 UTC, aliciabremer commented on routemodel/elevations/README.md
> +## User Guide
The documentation looks really good - very easy to follow for anyone else that wants to use the code!

2022-10-15 17:33 UTC, aliciabremer commented on routemodel/elevations/elevations.py
> +            coordinates using the desired number of intervals between the said coordinates. The i-th entry represents
I think this might be missing the rest of the sentence - I'm sure it works, but I was wondering why the cases differ when i is 0 and i is not 0, which I assume relates to what the i-th entry is

2022-10-15 17:33 UTC, aliciabremer commented on routemodel/tests/test_elevations.py
> +import sys
Nice tests!

2022-10-15 19:08 UTC, ryan-lam commented
@aliciabremer Done fixes

2022-10-15 19:48 UTC, probro27 approved these changes
Looks good to me. Great job @ryan-lam with the code and the documentation. 
If everyone approves then we can merge it :)

2022-10-16 17:08 UTC, aliciabremer approved these changes
Changes look good!

2022-10-16 17:13 UTC, merged