Process Routebook Loops
uw-midsun/strategy_xv pull request #7
Opened 2022-10-22 23:46 UTC by kevinchen220

2022-10-29 15:27 UTC, aliciabremer requested changes

2022-10-29 15:27 UTC, aliciabremer commented on benefitCostScore/convertData.py
> +def convertData(file):
Code and tests look great - good work! To possibly be able to reuse code in the future and for clarity, my one piece of feedback would be to split the tasks in convertData into smaller functions that get called - for example, into functions that clean up speed data, get number of stops, etc. That way, these functions can also be tested individually given smaller pieces of data!

2022-11-01 03:10 UTC, probro27 requested changes
Hey @kevinchen220 good job separating the functions. Could you add type annotations to the parameters so that code is better documented for people to use.
Also if possible could you add tests for all of the smaller functions. 
Thanks.

2022-11-18 01:37 UTC, probro27 approved these changes
LGTM! 
I'll let Alicia review the code first before merging but I think it's pretty good. 
The poetry.lock issue will be resolved soon. Then you can merge in the PR.

2022-11-18 01:37 UTC, probro27 approved these changes
LGTM! 
I'll let Alicia review the code first before merging but I think it's pretty good. 
The poetry.lock issue will be resolved soon. Then you can merge in the PR.

2022-11-19 19:17 UTC, aliciabremer commented
This looks good to me too! Nice work Kevin!

2022-11-19 19:17 UTC, aliciabremer approved these changes

2022-11-26 02:30 UTC, probro27 commented
@kevinchen220 Sorry to get back to you on this. So I automated the tests that you wrote so that they run whenever a new pull request comes in. Looks like your test fail, so you might wanna check it out, before we can approve the pull request. I resolved all of the merge conflicts so first please do `git pull` on this branch and then start working on figuring out the errors in the tests.

2022-11-27 20:56 UTC, merged