STRAT15-65 Completed Weather API call
uw-midsun/strategy_xv pull request #8
Opened 2022-10-27 17:33 UTC by KennethRuan

2022-10-29 18:27 UTC, probro27 commented
@KennethRuan I have left some reviews. 
Great job with the API calls and making tons of helper functions and providing the amazing documentation. 
Could you consider making a class called Weather and making these as member functions. That way we can have a better architecture. 
Also consider adding a new line at the end of every file. That way there are no issues when we put them in a linux environment.

2022-10-31 23:35 UTC, probro27 requested changes
Hey @KennethRuan, 

So yeah great job cleaning up the code. Everything looks good. 

Though my recommendation would be to if possible change this to a class model. That way we just need to import the class to get access to the functions. Also can we have that can request specific information from the API. Right now we are getting all of the information using get_weather. But I would prefer if we could specify what fields do we want. 

Would appreciate if you could make the changes. Thanks :)

2022-10-31 23:36 UTC, probro27 commented on routemodel/weather_forecast/get_weather.py
> +def get_weather(lat, lon, timestep, forecast_range=""):
Could you make separate helper functions for this one since this function is really long and super complex.

2022-11-01 04:34 UTC, probro27 approved these changes
Great job @KennethRuan. Really good work. 
I think this should be good enough.

2022-11-01 17:58 UTC, probro27 commented
@KennethRuan Do you know anything about the changes in `poetry.lock` file? 
They are causing some merge conflicts.

2022-11-01 18:16 UTC, KennethRuan commented
> @KennethRuan Do you know anything about the changes in `poetry.lock` file? They are causing some merge conflicts.

@probro27 I'm not entirely sure what the changes in `poetry.lock` are from. The only external library that I use is the `dateutil` extension, which I believe already exists in the version of `poetry.lock` on the main branch.

2022-11-02 00:44 UTC, rodrigotiscareno commented
This looks really great - good job! We're looking into resolving the poetry.lock issues this week. Also looking into adding secret management within Github and maybe having a general Midnight Sun Strategy email for our API keys :)

2022-11-25 23:54 UTC, probro27 commented
@KennethRuan can you change your code to use environment variables using python-dotenv as I have done in https://github.com/uw-midsun/strategy_xv/pull/19 instead of adding it in the config file?
That way I can add the environment variable to github actions and ensure that the tests work perfectly. 
Thanks :)

2022-11-27 01:22 UTC, KennethRuan commented
> @KennethRuan can you change your code to use environment variables using python-dotenv as I have done in #19 instead of adding it in the config file? Add the API key as TOMORROW_IO_API_KEY. That way I can add the environment variable to github actions and ensure that the tests work perfectly. Thanks :)

Will do!

2022-11-29 19:55 UTC, probro27 requested changes
Great job updating the environment variable use @KennethRuan. Could you just update the documentation a bit as well so we can merge this PR in.

2022-11-29 19:55 UTC, probro27 commented on routemodel/tests/test_weather.py
> +- The API key is retrieved from config.py, refer to the README inside weather_forecast for specifics
Hey @KennethRuan please update the documentation that we don't need to create `config.py`

2022-11-29 19:55 UTC, probro27 commented on routemodel/weather_forecast/README.md
> +Then, create a `config.py` file in the same directory as `get_weather.py` and store your API Key as a string.
Here as well!

2022-11-30 04:23 UTC, probro27 approved these changes
LGTM! Thanks a lot @KennethRuan. 
I'll merge it in.

2022-11-30 04:23 UTC, merged